### ISSUE TITLE
In api 22 and api 23 widget crash 

### ISSUE THREAD

**Issue by mozhi1364** [sAleksovski/react-native-android-widget#104]
Thanks a lot for this great library .I found out that it fixed in version 0.13.2 but in new version crash

**Comment by sAleksovski** [comment]
What version are you using? 
What error do you get? 
Can you share the stacktrace?

**Comment by mozhi1364** [comment]
I have problem with api 22 and 23 in latest version 0.14.1 the error is not catch in javascript ,in android studio i could see the error 
   `   E  Exception in native call
                                                                                                    java.lang.RuntimeException: Could not invoke AndroidWidget.drawWidgetById
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:381)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                                                    	at android.os.Looper.loop(Looper.java:148)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Ja`

**Comment by mozhi1364** [comment]
but in version 0.14.0 and 0.13.2 is ok .Thank You for This Amazing Library!

**Comment by sAleksovski** [comment]
Can you share the full log? 
I see a mention of `drawWidgetById`, but not what's causing the error. 

No plans for iOS support.

**Comment by mozhi1364** [comment]
i don't receive more log the error not get caught in try catch in java script .but if you test it on emulator api 22 and 23 you can see the crash

**Comment by sAleksovski** [comment]
This should be fixed in `0.14.2`
