### ISSUE TITLE
App crashes on production build with new architecture on React Native 0.76

### ISSUE THREAD

**Issue by sAleksovski** [sAleksovski/react-native-android-widget#110]
Stacktrace:

```
24-11-19 23:30:42.930  8160-8267  AndroidRuntime          com.androidwidgetexampleexpo         E  FATAL EXCEPTION: mqt_native_modules
	Process: com.androidwidgetexampleexpo, PID: 8160
	com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: Could not enqueue microtask because they are disabled in this runtime, js engine: hermes, stack:
	setImmediate@1:302007
	startHeadlessTask@1:354056
	__callFunction@1:107712
	anonymous@1:106154
	__guard@1:107094
	callFunctionReturnFlushedQueue@1:106112
	
		at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.kt:52)
		at com.facebook.jni.NativeRunnable.run(Native Method)
		at android.os.Handler.handleCallback(Handler.java:958)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
		at android.os.Looper.loopOnce(Looper.java:205)
		at android.os.Looper.loop(Looper.java:294)
		at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
		at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
		at java.lang.Thread.run(Thread.java:1012)
```

**Comment by mefjuu** [comment]
Really crashes? On RN .77 with `newArchEnabled=true` widget updating has no effect (there is no crash though)

**Comment by gpercem** [comment]
I can confirm the crashes. I am running expo 52.0.25 with react native 0.76.7 with newArchEnabled=true, and having render issues on widget with constant crashes. I didn't try upgrading react native to 0.77 but turning off the new architecture solved the crash and rendering issues.

**Comment by pelinche** [comment]
Same happens here (Expo 52.0.36, react-native 0.76.6 - newArchEnabled = true).

Does anyone have any news?

**Comment by tomas223** [comment]
As a potential workaround polyfill for `global.setIntermediate(...)` can be used. See my [comment here](https://github.com/sAleksovski/react-native-android-widget/issues/65#issuecomment-2772648358)

**Comment by sAleksovski** [comment]
@tomas223 Thanks for the investigation. I'm not sure this is related to jsc/hermes, since it works on old architecture.
I'm not sure why HeadlessJS does not work on new architecture, but works on old one.

**Comment by sAleksovski** [comment]
Looks like the issue is fixed in react native 0.79.0
I released a new version (0.16.0) that uses react native 0.79.0 for the example app, and a prerelease expo 53 that has support for react native 0.79.0, and I no longer see the crash.
