### ISSUE TITLE
Widgets do not appear on the home screen only on the device

### ISSUE THREAD

**Issue by explorer-cat** [sAleksovski/react-native-android-widget#44]
Hi, I'm using the library well
However, when you add an app from a certain point in time, the widget will not be drawn on the screen
In the emulator, the widget appears well on the home screen, but the home screen UI does not appear on the actual device because it is built and deployed

Can I see the logs when I add widgets from this library?

I updated the library to the latest version
"react-native": "0.71.6", is being used

**Comment by explorer-cat** [comment]
Do you happen to have a channel where I can talk to you in real time? Our app will be launched next week, please

**Comment by sAleksovski** [comment]
Can you check the logcat logs?

Do you correctly handle the WIDGET_ADDED, WIDGET_UPDATE... events?

Is the app crashing? Any logs?

**Comment by explorer-cat** [comment]
It works well when you add widgets in debug mode after connecting the emulator or USB, but the widget is not visible in the app registered in the market in release mode.

**Comment by sAleksovski** [comment]
I don't think I completely understand.

You add the widget on the home screen, and it does not render? What do you see?
Can you send a screenshot/video?

You can enable logs using https://stackoverflow.com/questions/25610936/enable-logcat-on-release-build-in-android-studio

**Comment by explorer-cat** [comment]
java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.utils.ResourceUtils.getInputStreamFromSource(ResourceUtils.java:102)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.utils.ResourceUtils.getBitmap(ResourceUtils.java:44)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.ImageWidget.getBitmapFromURL(ImageWidget.java:44)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.ImageWidget.applyProps(ImageWidget.java:27)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.BaseWidget.<init>(BaseWidget.java:36)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.BaseWidget.<init>(BaseWidget.java:40)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.widget.ImageWidget.<init>(ImageWidget.java:17)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.getBaseWidget(WidgetFactory.java:104)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildWidget(WidgetFactory.java:71)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildChildren(WidgetFactory.java:125)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.getBaseWidget(WidgetFactory.java:108)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildWidget(WidgetFactory.java:71)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildChildren(WidgetFactory.java:125)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.getBaseWidget(WidgetFactory.java:108)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildWidget(WidgetFactory.java:71)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildChildren(WidgetFactory.java:125)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.getBaseWidget(WidgetFactory.java:108)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildWidget(WidgetFactory.java:71)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildChildren(WidgetFactory.java:125)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.getBaseWidget(WidgetFactory.java:114)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildWidget(WidgetFactory.java:71)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.builder.WidgetFactory.buildWidgetFromRoot(WidgetFactory.java:41)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.RNWidget.drawWidget(RNWidget.java:62)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.reactnativeandroidwidget.AndroidWidgetModule.drawWidgetById(AndroidWidgetModule.java:41)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at java.lang.reflect.Method.invoke(Native Method)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.facebook.jni.NativeRunnable.run(Native Method)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at android.os.Handler.handleCallback(Handler.java:942)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at android.os.Looper.loopOnce(Looper.java:226)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at android.os.Looper.loop(Looper.java:313)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
2023-11-16 11:27:40.548 25170-25429 System.err              com.yhdatabase.ybe                   W  	at java.lang.Thread.run(Thread.java:1012)

**Comment by explorer-cat** [comment]
![633104D9-C14F-48DB-BA02-C28B25CB8DD9](https://github.com/sAleksovski/react-native-android-widget/assets/55500077/1f6d19ee-963f-447b-9c77-0698c60d358a)
![24246801-63D8-4821-890D-8DD28FDFE556](https://github.com/sAleksovski/react-native-android-widget/assets/55500077/d80b19c2-fe96-4fb1-9bc8-aa1b7e0afc69)


One connected USB and ran through react-native run-android, and one was an app distributed to the Play Store.

**Comment by sAleksovski** [comment]
According to the log, there is a problem with some image, and the way it is referenced. How do you use the ImageWidget?

**Comment by sAleksovski** [comment]
This looks like some kind of monorepo setup.

While you are in development mode, the images are loaded from the dev server. But when you create a production build, the image should be bundled in the apk.

I think that the problem is that React Native is not bundling the image in the production app.
Is the image inside the app directory? Can you move it inside the app directory if not? Or place it next to the widget file?

Also, from your screenshots it looks like `widget_alert_icon` is the red circle.
If so, you can try replacing it with:

```jsx
<FlexWidget
  style={{
    backgroundColor: '#ff0000',
    height: 16,
    width: 16,
    borderRadius: 8,
    marginRight: 5
  }}
/>
```

**Comment by explorer-cat** [comment]
I think the problem with the image is correct I want to take the image from the external http link and use it in the widget, but can I use the <ImageWidget> tag only for the local image?

<ImageWidget
image={require('https://i.pravatar.cc/150?img=3')}
/>

Can I use it this way?

**Comment by explorer-cat** [comment]
I successfully created a widget by processing it with an external url without loading images from the app! Thank you for your kind response!
