### ISSUE TITLE
Using array.map in render throws an error

### ISSUE THREAD

**Issue by mark-yacoub** [sAleksovski/react-native-android-widget#8]
When I called a function called `renderTasks()` inside the FlexWidget, and `renderTasks` does `return myarray.map( /* return a FlexWidget */)` i get this error
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property '__name__' of undefined
TypeError: Cannot read property '__name__' of undefined
    at buildWidgetTree (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130663:25)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130677:31)
    at map (native)
    at buildWidgetTree (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130676:13)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130745:181)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:20674:26)
    at _next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:20693:29)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:20698:14)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/43l2p1y5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/43l2p1y5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/43l2p1y5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:20690:25)
    at apply (native)
    at _init (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130751:27)
    at apply (native)
    at init (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130741:27)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:130753:11)
    at commitHookEffectListMount (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:71801:38)
    at commitPassiveMountOnFiber (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:72827:44)
    at commitPassiveMountEffects_complete (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:72799:40)
    at commitPassiveMountEffects_begin (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:72789:47)
    at commitPassiveMountEffects (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:72779:40)
    at flushPassiveEffectsImpl (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:73973:34)
    at flushPassiveEffects (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:73933:43)
    at performSyncWorkOnRoot (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:73422:28)
    at flushSyncCallbacks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:64803:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:64788:29)
    at scheduleUpdateOnFiber (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:73136:47)
    at updateContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:75195:32)
    at render (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:75706:24)
    at renderElement (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:3068:77)
    at renderApplication (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:45764:27)
    at run (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:45407:42)
    at runApplication (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:45458:28)
    at apply (native)
    at __callFunction (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:2444:36)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:2205:31)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:2395:15)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.metanify&modulesOnly=false&runModule=true:2204:21)
```

**Comment by sAleksovski** [comment]
Can you share your widget, or just a part of the widget that I can try to see why you get the error?

You can use only the [widget primitives](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-design), and custom components that use only the widget primitives. See the [Hooks section here](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-design) .

You wouldn't need a `renderTasks` function, you can create a `Tasks` component.

```jsx
function Tasks({ tasks }) {
  return (
    <FlexWidget>
      {tasks.map(x => <FlexWidget><TextWidget ... /></FlexWidget>
    </FlexWidget>
  );
}
```

Then the `Tasks` component can be used in your widget.

```jsx
function MyWidget({ tasks }) {
  return (
    <FlexWidget>
      <Tasks tasks={tasks} />
    </FlexWidget>
  );
}
```

**Comment by mark-yacoub** [comment]
thanks for the example.
So here is what im currently doing (but your example is pretty nice and im gonna use it)
```
  const renderTask = idx => {
    if (idx >= tasksForDate.length) {
      return null;
    }

    const task = tasksForDate[idx];
    const taskCompleted = task.isCompleted;
    const taskCompletedText = taskCompleted ? '✅' : '❌';
    const taskCompletedColor = taskCompleted ? '#00FF00' : '#FF0000';

    return (
      <FlexWidget style={styles.taskRowContainer}>
        <TextWidget text={task.name} style={{fontSize: 16}} />
        <TextWidget
          text={taskCompletedText}
          style={{fontSize: 16, color: taskCompletedColor}}
          clickAction={ACTIONS.TOGGLE_TASK}
          clickActionData={{task_id: task.task_id, date: date.toString()}}
        />
      </FlexWidget>
    );
  };

  return (
    <FlexWidget style={styles.container}>
      {renderDate()}
      {/* There is bug in using array.map so just render as many as we can. */}
      {renderTask(0)}
      {renderTask(1)}
      {renderTask(2)}
      {renderTask(3)}
      {renderTask(4)}
      {renderTask(5)}
      {renderTask(6)}
    </FlexWidget>
  );
};
```

what didn't work is this:
```
  const renderTasks = () => {
    return tasksForDate.map((task, idx) => {
      <TextWidget key={idx} text='↗️' />;
    });
  };

  return (
    <FlexWidget
      style={{
        height: '300',
        width: 'match_parent',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        overflow: 'auto',
        paddingVertical: 5,
        flex: 1,
      }}>
      {renderDate()}
      {renderTasks()}
    </FlexWidget>
  );
};
```

**Comment by sAleksovski** [comment]
`map` is working, in your example you don't have a return statement.
It should be 

```jsx
  const renderTasks = () => {
    return tasksForDate.map((task, idx) => {
      return <TextWidget key={idx} text='↗️' />;
    });
  };
```
or
```jsx
  const renderTasks = () => {
    return tasksForDate.map((task, idx) => <TextWidget key={idx} text='↗️' />);
  };
```

I couldn't reproduce the issue with the code you shared. The following code works just fine (both with and without the second `return` in `renderTasks`):

```jsx
const renderTasks = () => {
  return [1, 2, 3].map((task, idx) => {
    return <TextWidget key={idx} text={`${task}`} />;
  });
};

function TestWidget() {
  return (
    <FlexWidget
      style={{
        height: '300',
        width: 'match_parent',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        overflow: 'auto',
        paddingVertical: 5,
        flex: 1,
      }}
    >
      {renderTasks()}
    </FlexWidget>
  );
}
```

If the second return is not present, the "tasks" are not rendered at all (because `renderTasks` returns `[undefined, undefined, ...]`.

Can you share the complete file (including mock for `tasksForDate`) that can be copied so I can see the problem, or just comment if you solve it by restructuring your code.
