### ISSUE TITLE
Error while building with expo

### ISSUE THREAD

**Issue by preetamra** [sAleksovski/react-native-android-widget#99]
`widgets.forEach(function (widget) {
            ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at withWidgets (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/react-native-android-widget/app.plugin.js:168:13)
    at withAndroidWidgets (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/react-native-android-widget/app.plugin.js:27:14)
    at withStaticPlugin (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:134:12)
    at /Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:18)
    at withConfigPlugins (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/@expo/config/build/plugins/withConfigPlugins.js:35:47)
    at fillAndReturnConfig (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/@expo/config/build/Config.js:229:78)
    at getConfig (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/@expo/config/build/Config.js:286:10)
    at Object.<anonymous> (/Users/apple/Desktop/Projects/WaterRemainderTest6/node_modules/expo-constants/scripts/build/getAppConfig.js:25:40)`

**Comment by preetamra** [comment]
i didnt configure the library correctly
